version: '3.4'

services:
  postgresql-data:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: DigiMed123
    ports:
      - 5434:5432

  evercoach.api:
    image: ${DOCKER_REGISTRY-}evercoachapi
    build:
      context: .
      dockerfile: EverCoach/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

